# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 679f22a7ea5aa43961498e743e46fb296aed96a25fbec0568c5d26b270b4fe24c170d1cad0d2ed45e39eecc7c3e92f38fb9692fdf3589f4c61587e70dd476701

test:
  secret_key_base: cca0881eb9cef92ab1cb39768c30103ee7f78bf0f4275a4d954b5fa14fcb72efddd618fc0b2376265f1e9c508f4ffc964b33ff3e07c7b662e62082d83f69dca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
